intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libzstd%lib{zstd}
import intf_libs += libppqsort%lib{ppqsort}
import intf_libs += libpdqsort%lib{pdqsort}
import intf_libs += robin-hood-hashing%lib{robin-hood-hashing}
import intf_libs += xxhash%lib{xxhash}
import intf_libs += liblz4%lib{lz4}
import impl_libs += libcapstone%lib{capstone}

# Upstream's TracyServer library (cmake/server.cmake). The profiler builds it
# with statistics.
#
./: libue{server}

libue{server}: hxx{** -GitRef} h{*} cxx{*} hxx{GitRef} \
               ../compat/h{capstone} ../public/common/{h hxx cxx}{*} \
               $impl_libs $intf_libs

# Version string the profiler prints along with the version (upstream
# generates it from the git revision).
#
hxx{GitRef}: in{GitRef}
{
  ref = "v$version.major.$version.minor.$version.patch"
}

# Build options.
#
# Like upstream, the server and public/common headers are also included
# without a directory (TracyServer's include directories).
#
cxx.poptions =+ "-I$out_base" "-I$src_base" "-I$src_root/public/common" \
                "-I$src_root/compat"

# System libraries of the server and common sources.
#
if ($cxx.target.system == 'mingw32')
  cxx.libs += -lws2_32 -lsecur32 -ladvapi32
elif ($cxx.target.class == 'windows')
  cxx.libs += ws2_32.lib secur32.lib advapi32.lib

if ($cxx.target.system != 'win32-msvc')
  cxx.libs += -pthread
