libs =
#import libs += libhello%lib{hello}

include ../../server/
import libs += libgetopt_port%liba{getopt_port}

exe{tracy-update}: {h hxx ixx txx cxx}{**} ../../getopt/h{getopt} \
                   ../../server/libue{server-nostats} $libs

# The server headers and GitRef.hpp are included without a directory, like
# with upstream's TracyServer include directories.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" \
                "-I$out_root/server" "-I$src_root/server" \
                "-I$src_root/public/common"

# Must match the server variant these tools link (server-nostats).
#
cxx.poptions += -DTRACY_NO_STATISTICS

# DbgHelp is used for offline symbol resolution on Windows.
#
if ($cxx.target.system == 'mingw32')
  cxx.libs += -ldbghelp
elif ($cxx.target.class == 'windows')
  cxx.libs += dbghelp.lib
