libs =
#import libs += libhello%lib{hello}

include ../../server/
import json_libs = nlohmann-json%lib{json}

./: exe{tracy-import-chrome tracy-import-fuchsia}

exe{tracy-import-chrome}: cxx{import-chrome} \
                          ../../server/libue{server-nostats} \
                          $json_libs $libs

exe{tracy-import-fuchsia}: cxx{import-fuchsia} \
                           ../../server/libue{server-nostats} \
                           $libs

# The server headers and GitRef.hpp are included without a directory, like
# with upstream's TracyServer include directories.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" \
                "-I$out_root/server" "-I$src_root/server" \
                "-I$src_root/public/common"

# Must match the server variant these tools link (server-nostats).
#
cxx.poptions += -DTRACY_NO_STATISTICS

# Upstream prints size_t values with PRIu64, which has the same width on
# 64-bit targets.
#
if ($cxx.class == 'gcc')
  obje{import-fuchsia}: cxx.coptions += -Wno-format
