intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libzstd%lib{zstd}
import intf_libs += libppqsort%lib{ppqsort}
import intf_libs += libpdqsort%lib{pdqsort}
import intf_libs += robin-hood-hashing%lib{robin-hood-hashing}
import intf_libs += xxhash%lib{xxhash}
import intf_libs += liblz4%lib{lz4}
import impl_libs += libcapstone%lib{capstone}

# Upstream's TracyServer library (cmake/server.cmake), shared by the tools.
# It is built in two variants since TRACY_NO_STATISTICS changes the layout
# of the server classes: the tools that do not need statistics (capture,
# import, update) use server-nostats, the others use server.
#
sources = TracyBroadcast TracyMemory TracyMmap TracyPrint TracySysUtil \
          TracyTaskDispatch TracyTextureCompression TracyThreadCompress \
          TracyWorker

./: libue{server server-nostats}

libue{common}: ../public/common/{h hxx cxx}{*}

libue{server}: hxx{** -GitRef} h{*} cxx{$sources} hxx{GitRef} \
               ../compat/h{capstone} libue{common} $impl_libs $intf_libs

libue{server-nostats}: hxx{** -GitRef} h{*} nostats/obje{$sources} hxx{GitRef} \
                       ../compat/h{capstone} libue{common} \
                       $impl_libs $intf_libs

# The nostats/ output directory must be declared explicitly for in-source
# builds (such as of the distribution).
#
for s: $sources
  nostats/obje{$s}: cxx{$s} fsdir{nostats/} $impl_libs $intf_libs

# Version string the tools print along with the version (upstream generates
# it from the git revision).
#
hxx{GitRef}: in{GitRef}
{
  ref = "v$version.major.$version.minor.$version.patch"
}

# Build options.
#
# Like upstream, the server and public/common headers are also included
# without a directory (TracyServer's include directories).
#
cxx.poptions =+ "-I$out_root" "-I$src_root" \
                "-I$out_base" "-I$src_base" "-I$src_root/public/common" \
                "-I$src_root/compat"

nostats/
{
  obje{*}: cxx.poptions += -DTRACY_NO_STATISTICS
}

# System libraries of the server and common sources.
#
if ($cxx.target.system == 'mingw32')
  cxx.libs += -lws2_32 -lsecur32 -ladvapi32
elif ($cxx.target.class == 'windows')
  cxx.libs += ws2_32.lib secur32.lib advapi32.lib

if ($cxx.target.system != 'win32-msvc')
  cxx.libs += -pthread
